version: '3'

services:
  # php, apache
  # mysqlに接続するときはlocalhost:3306で接続するのかな？
  php:
    image: php:7.2.7-apache
    container_name: php_apache
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html

  # MYSQL
  # またもや起動しない
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      TZ: 'Asia/Tokyo'
    command: mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
